### ISSUE TITLE
The mallet passes through the table !!

### ISSUE THREAD

**Issue by zerubeus** [Ybalrid/virtual-air-hockey#1]
this need to be fix as soon as possible :

defining the table to be a static object so any other static or dynamic object can't passes through !

**Comment by Ybalrid** [comment]
Looks like just a plane is not enough static geometry to detect the collision. I'll try updating the table mesh to fix this

**Comment by zerubeus** [comment]
I dont know why but now the paddle don't passes through the table anymore ...

**Comment by Ybalrid** [comment]
Puck and Paddle on the table.
