### ISSUE TITLE
get the X/Y/Z position of the AnnPlayer and use it in netPlayer class

### ISSUE THREAD

**Issue by zerubeus** [Ybalrid/virtual-air-hockey#11]
All is in the title I've tried to do this with no success, this is what i have so far and still throwing ERRORS any  enhancement are welcome and please replay under 24h max, 

``` cpp
PlayerStc NetPlayer::getNetData() 
{
        auto engine(AnnEngine::Instance());
        PlayerStc data;
        data.X = (float)engine->getPlayer()->getPosition();
}
```

**Comment by Ybalrid** [comment]
getPosition() returns an AnnVect3.

AnnVect3 has 3 public members "x", "y", "z" that are of "Ogre::Real" type. Ogre::Real is the same thing as a float.

So if you want to get the X componant of the player's position it's just "getPlayer()->getPosition().x"

But you don't need the position of the AnnPlayer. AnnPlayer doesn't move in this game, it's a static VR experience ;-)
