### ISSUE TITLE
get position of a levelContent 

### ISSUE THREAD

**Issue by zerubeus** [Ybalrid/virtual-air-hockey#14]
how to get the position of the sindbad for exemple ? 

``` cpp
//Load Sinbad:
    auto Sinbad (engine->createGameObject("Sinbad.mesh"));
    Sinbad->setUpPhysics(100, phyShapeType::boxShape);
    //Add it to the level list
    levelContent.push_back(Sinbad);
```

**Comment by Ybalrid** [comment]
Sinbad->pos() return an AnnVect3 object. I really need to review the AnnGameObject class to add naming consistency.

**Comment by Ybalrid** [comment]
But here the "Sinbad" pointer only exist within the scope of the "load" method. So if you want to access "Sinbad" within the "runLogic" method, you need to make it a member of the class.

More directly, you need to declare, inside the class header a "AnnGameObject\* Sinbad;"

**Comment by Ybalrid** [comment]
@zerubeus if you pull&recompile Annwyvn, you can juse "->getPosition()", "->setPosition(AnnVect3)" and "->setPosition(float, float, float)".

The using of "pos" and "setPos" will now generate a "deprecated" warning. I'm trying to harmonise the naming conventions everywhre inside Annwvyn. And the "AnnGameObject"'s API really need some work in this direction... :wink:
