### ISSUE TITLE
Need a game startup menu

### ISSUE THREAD

**Issue by Ybalrid** [Ybalrid/virtual-air-hockey#15]
User need to be able to set option at the start up of a game.

There is no 2D GUI usable "out of the box" for doing this. 

Need to use the level manager and an event listener to make something that will work

**Comment by zerubeus** [comment]
@Ybalrid do you need a design for the GUI ? i can Photoshoped if you want beware that the menu needs to be done as soon as possible, for now I see that we have just the cursor !

**Comment by zerubeus** [comment]
@Ybalrid the user needs to be able to chose between two option , typing the server name or the server IP , and a checkbox with UDP or TCP , all Networking erreur will be displayed in AnnDebug() !

**Comment by Ybalrid** [comment]
I know. 

The idea is that I write the network configuration inside an object. You'll take it as an argument of the method that actually "start the network"

**Comment by Ybalrid** [comment]
Just something that will hold
`std::string hostAddress;`
`bool useUDP; //if false, assume the network is using TCP instead`

I'm bodging something to get buffered keyboard input from the input library used by Annwvyn. I added an "AnnTextInputer" class inside Annwvyn's eventManager. So the code I'm writing will only compile after pulling the changes from Annwvyn's master branch. No big deal.
