### ISSUE TITLE
paddle shape don't have to be cylinder shape 

### ISSUE THREAD

**Issue by zerubeus** [Ybalrid/virtual-air-hockey#3]
Like you can see in the image below the shape of our paddle is cylinder so when he reach the table we dont get the needed alignement , this also need a rework with blender &/or Annwvyn 

``` cpp
paddle->setUpPhysics(1, cylinderShape);
```

I'm wondering if we can create a new shape type depend on the 3D model used ? so for exemple instead of cylinderShape we use something like paddleShape. 

![Paddle test](http://s30.postimg.org/ymcjupztt/a_test.png)

**Comment by Ybalrid** [comment]
I think "convexShape" should do the trick

**Comment by Ybalrid** [comment]
But yeah, kind of weird actually, I was pretty sure cynlinders were generated along the Y axis...

**Comment by Ybalrid** [comment]
![ss 2016-01-03 at 09 50 14](https://cloud.githubusercontent.com/assets/1816251/12078005/73941f9a-b1ff-11e5-8deb-b56f932e6d61.jpg)

Better now.

**Comment by zerubeus** [comment]
we don't close issues , we just add the resolved label
